name: 'Imagemagick Configuration'
description: 'Installs and configures Imagemagick for Drupal.'
type: 'System'
install:
  - imagemagick
config:
  actions:
    # Update system's image toolkit to imagemagick from the default gd.
    system.image:
      simple_config_update:
        toolkit: imagemagick
    # Set the quality to 100 from the default 75.
    imagemagick.settings:
      simple_config_update:
        quality: 100
