name: 'Imagemagick Configuration'
description: 'Installs and configures Imagemagick for Drupal.'
type: 'Site'
install:
  - imagemagick
config:
  strict: false
  actions:
    # Update system's image toolkit to imagemagick from the default gd.
    system.image:
      simpleConfigUpdate:
        toolkit: imagemagick
    # Set the quality to 100 from the default 75.
    imagemagick.settings:
      simpleConfigUpdate:
        quality: 100
