name: 'Imagemagick Configuration'
description: 'Installs and configures Imagemagick for Drupal.'
type: 'Site'

install:
  - imagemagick
config:
  import:
    imagemagick: "*"
    file_mdm: "*"
    sophron: "*"
  actions:
    # Update system's image toolkit to imagemagick from the default gd.
    system.image:
      simple_config_update:
        toolkit: imagemagick
    # Set the quality to 100 from the default 75.
    imagemagick.settings:
      ensure_exists:
        id: imagemagick.settings
      simple_config_update:
        quality: 100
